### ISSUE TITLE
Incompatible with Python 3.10 due to old dependency to pyhumps

### ISSUE THREAD

**Issue by voneiden** [Javidjms/influxable#14]
Currently using pyhumps==1.3.1. Pyhumps 3.10 incompatibility was fixed in https://github.com/nficano/humps/pull/79/commits/053c6b2423de3352b6900ee221cae5382e8c1e2b

Moving to pyhumps==1.6.1 should resolve the issue. Primary changes are that py3.4 support is dropped and py3.10+ support is enabled.

**Comment by Javidjms** [comment]
Yeah nice.

What about if we also set upper strict requirement for pyhumps like this : pyhumps>=1.6.1

**Comment by voneiden** [comment]
Your call - I just went with the minimum version increase to get things working.  Possibly needs a quick review to ensure that the major version increase (to 3.7.3) doesn't introduce any API backwards incompatibility with influxable. I checked only that 1.6.1 didn't seem to introduce any breaking changes compared to 1.3.1
