### ISSUE TITLE
Any plans to support group by and order by?

### ISSUE THREAD

**Issue by Gigatron** [Javidjms/influxable#2]

**Comment by Javidjms** [comment]
Hi,

The function "group_by", "order_by" and "into" should be released in the Milestone 1.3.0 .

The project is currently suspended for inactivity.

I will keep you in touch when the project will restart.

Thanks.

Javid.

**Comment by Javidjms** [comment]
Hi,

I have just added the group_by, "order_by" and "into" in the last release.

Javid.
