### ISSUE TITLE
Error inserting Chinese field

### ISSUE THREAD

**Issue by zshuaia** [Javidjms/influxable#3]
Body ('计算器') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.

**Comment by Javidjms** [comment]
Okay thanks for the feedback.

Did you encounter this error when saving data with the bulk_save() method or BulkInsertQuery class.

In any case, i will fix it with body.encode.

**Comment by Javidjms** [comment]
Hi the problem has been fixed in the last release 1.2.1
