### ISSUE TITLE
Pinned requirements is old

### ISSUE THREAD

**Issue by AllanLeanderRostockHansen** [Javidjms/influxable#5]
The pinned version of Numpy and Pandas specified in _requirements.txt_ is quite old (I haven't checked the rest of the specified libraries).
Is it possible that [less strict requirements ](https://www.python.org/dev/peps/pep-0440/#compatible-release) would work as well?

**Comment by Javidjms** [comment]
Hi, thanks for your feedback and I set less strict requierements for Numpy and Pandas.

https://github.com/Javidjms/influxable/releases/tag/1.3.1
