### ISSUE TITLE
Is this complaint  with PEP 249

### ISSUE THREAD

**Issue by HassankSalim** [Javidjms/influxable#6]
if its complaint with PEP 249 with help with integration with ORMs like sqlalchemy

**Comment by HassankSalim** [comment]
if its complaint with PEP 249 with help with integration with ORMs like sqlalchemy

**Comment by Javidjms** [comment]
I tried to build an app which looks like Django ORM (I should have added a note about this).

I could add an integration with sqlalchemy or Django but i would like to deliver this app quicky.

If you have any recommandations, i am happy to apply them.

Javid

**Comment by HassankSalim** [comment]
could you tell how you integrated with Django ORM.

**Comment by Javidjms** [comment]
I didn't integrated with the Django ORM but I was inspired by Django Models

[https://docs.djangoproject.com/en/3.1/topics/db/models/](https://docs.djangoproject.com/en/3.1/topics/db/models/)

**Comment by HassankSalim** [comment]
got it :+1: , thanks for the reply
