### ISSUE TITLE
 Authorization Failed (Bad credentials)

### ISSUE THREAD

**Issue by AntmanTmp** [Javidjms/influxable#9]
Hi, there
There are a few questions to ask, thank you 

1. Which versions of influxDB will this library be compatible with?
2. create_connection  method of Connection class not implement, see [here](https://github.com/Javidjms/influxable/blob/8a2f798cc5ae12b04f803afc84d7e064a3afd250/influxable/app.py#L12)
3.  check connection whether reach not take auth into consideration, see [here](https://github.com/Javidjms/influxable/blob/8a2f798cc5ae12b04f803afc84d7e064a3afd250/influxable/connection.py#L31)

My influxDB is OSS 2.0
When we use Measurement to insert points, through the static analysis of the code, we find that the Influxable singleton will be obtained before insert is executed. This singleton will obtain the identity authentication information from the environment variable and try to see if the connection is reachable. However, the identity authentication information is not carried in any parameters of the request which wrapped by InfluxDBApi, which will eventually lead to a 401 error.

Influx 1.x 

In the version 1.x of the API, it is clearly stated that InfluxQl is compatible with OSS 2.0 and should also carry identity authentication information for query. In order not to expose the privacy used, it is recommended to use the Token authentication method. Offical docs below:

[influxdb 1.x query](https://docs.influxdata.com/influxdb/v2.0/reference/api/influxdb-1x/query/)
[influxdb 1.x auth](https://docs.influxdata.com/influxdb/v2.0/reference/api/influxdb-1x/#authentication)

**Comment by AntmanTmp** [comment]
From the DockerFile I get you will use the 1.7.7 version of InfluxDB

**Comment by Javidjms** [comment]
Hi

I would like to know which exact version of InfluxDb have you installed.

Like you said, I am using the 1.7.7 but i initially started to use the 1.5.4.

Influxable is compatible between 1.5.x and 1.8.x. It is not yet compatible with the new api 2.x (it was not released at that time).

The create_connection method is implemented but not yet used. I planned to use it for multiple connection and the ability to switch it.


For the 1.x api, sending the query « SHOW DATABASES » without credential for authentication-enabled will return an unauthorized 401.

I will investigate about with OSS 2.0 compatibility with the token authentification.

Javid.

Replied with Iphone.

**Comment by AntmanTmp** [comment]
Thanks for your reply.
Token authentification is much better than username and password.
influxable is good and would be better if it is compatible with OSS2.0

It`s a nice work  👍

**Comment by Javidjms** [comment]
Hi I just pushed my code and add the integration with the OSS 2.0 token.

You have to use the env INFLUXDB_AUTH_TOKEN and set your token.

I added a special section in the README about the configuration of your bucket/dbrp.

Remember that is experimental because the api v1 of the OSS is limited (database creation is not allowed, only through dbrp).

Queries and Points work fine.

I close this this issue. If needed, we can open a new issue about OSS 2 limitation.

Javid
